name = "grocery-list"
main = "src/main.tsx"
compatibility_date = "2026-03-06"
compatibility_flags = [ "nodejs_compat" ]


[[durable_objects.bindings]]
name = "GROCERYLIST"
class_name = "GroceryList"

[[migrations]]
tag = "v1"
new_classes = ["GroceryList"]

[assets]
directory = "./dist"

[build]
command = "npm run build"
